name: Run cronjob

on:
  schedule:
    - cron: '15 0 * * *' # Runs every 00:15
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  run-cronjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run cronjob script
        run: python scripts/cronjob.py

      - name: Configure Git
        run: |
          git config --global user.name FJakovljevic
          git config --global user.email ${{secrets.EMAIL}}

      - name: Commit changes
        run: |
          git add data/runs.csv
          git add data/EAukcija_dump.csv
          git commit -m "Updating Data"
     
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
